frame_materials:
  bottom:
    vertex: NETHERITE_BLOCK
    edge: LAPIS_BLOCK
    face: LAPIS_BLOCK
  side:
    edge: IRON_BLOCK
    face: GLASS
  top:
    vertex: REDSTONE_BLOCK
    edge: IRON_BLOCK
    face: GLASS

limits:
  width: 7
  height: 7

terminal:
  texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjk4ZTFkYzNlZDA0OWE1MDZjNmE2NmU3MmRlYmE3ZmFlOThhODVmOGQ5M2I4NDc3YmZlYThiNzE2ZWZiYmNlIn19fQ==
  name: &bTerminal
  lore: []