name: ShulkerStorage
version: @version@
main: ru.melonhell.shulkerstorage.ShulkerStorage
api-version: 1.13
authors: [ MelonHell ]
depend:
  - RedLib
commands:
  sstest:
    usage: /sstest
    permission: op